name: cab

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  cab:
    runs-on: ubuntu-latest
    steps:
      - name: C
        uses: actions/checkout@v2

      - name: B
        run: |
          git config --local user.email "51532767+L1bws@users.noreply.github.com"
          git config --local user.name "L1bws"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "I'm king of the world!"
          git push